apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-deploy
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deploy
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.tag }}
        name: flaskex
        ports:
        - containerPort: {{ .Values.podPort }}
        