apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.podPort }}
  selector:
    app: {{ .Release.Name }}-deploy
  type: {{ .Values.serviceType }}