---
apiVersion: v1
kind: Pod
metadata:
  namespace: event-demo
  name: nginx1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2


---
apiVersion: v1
kind: Pod
metadata:
  namespace: wordpress
  name: wordpress
spec:
  containers:
  - name: nginx
    image: wordpress:php8.2


---
apiVersion: v1
kind: Pod
metadata:
  namespace: wordpress
  name: mistake
spec:
  containers:
  - name: nginx
    image: wordpres:php8.2