apiVersion: batch/v1
kind: Job
metadata:
  name: terraform
spec:
  template:
    spec:
      containers:
      - name: init
        image: hashicorp/terraform
        command: ["terraform",  "init"]
      - name: apply
        image: hashicorp/terraform
        command: ["terraform",  "fmt"]
      restartPolicy: Never
  backoffLimit: 4

