---
apiVersion: v1
kind: Pod
metadata:
  namespace: event-demo
  name: nginx1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
  tolerations:
  - key: Dedicated
    operator: Equal
    value: approved
    effect: NoSchedule  