---
# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: sleepy
    image: alpine
    command: ['sleep', '3']  
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: nginx2
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: nginx3
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: nginx4
    image: nginx:1.14.2
    ports:
    - containerPort: 80
