apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: config
    configMap:
      name: nginx-config
      items:
      - key: "nginx.conf"
        path: "nginx.conf"
  containers:
  - image: nginx
    name: nginx-pod
    env:
      - name: PROXY_STATUS
        valueFrom:
          configMapKeyRef:
            name: nginx-config          
            key: proxy_status
    volumeMounts:
      - name: config
        mountPath: "/etc/nginx.conf"
        subPath: nginx.conf
        readOnly: true

     
