---
# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: artemis
  labels: 
    app: demo
  annotations:
    created_by: "devops"
spec:
  containers:
  - name: artemis
    image: farrukhsadykov/artemis:latest
    ports:
    - containerPort: 5000
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet: null
      tcpSocket:
        port: 5000
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet: null
      tcpSocket:
        port: 5000
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    livenessProbe:
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet: null
      tcpSocket:
        port: 6379
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
      httpGet: null
      tcpSocket:
        port: 6379

        
# kubectl apply -f artemis.yaml 