---
# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app: demo
  annotations:
    created_by: "devops"
spec:
  nodeSelector:
    cpu: optimized
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

#  k apply -f pod_on_specific_node.yaml --force
