apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
spec:
  ports:
  - port: 80
    nodePort: 30090
    targetPort: 80
  selector:
    label: dev
  type: LoadBalancer
  externalTrafficPolicy: Local