apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      label: dev
  template:
    metadata:
      labels:
        label: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80