apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: web-app-deploy
    spec:
      containers:
      - image: ikambarov/web-app:1.0.0
        name: web-app