apiVersion: v1
kind: Pod
metadata:
  labels:
    run: terraform-pod
  name: terraform-pod
spec:
  serviceAccountName: terraform
  containers:
  - image: hashicorp/terraform
    command: ["sleep", "1000000"]
    name: terraform